In [2]:
with open ("/home/jdiego/Documentos/MACHINE_LEARNING_DATA_SCIENCE/UNZIP_FOR_NOTEBOOKS_FINAL/One.txt") as mytext: 
    words_one = mytext.read().lower().split()
    uni_words_one = set(words_one)


In [3]:
with open ("/home/jdiego/Documentos/MACHINE_LEARNING_DATA_SCIENCE/UNZIP_FOR_NOTEBOOKS_FINAL/Two.txt") as mytext2: 
    words_two = mytext2.read().lower().split()
    uni_words_two = set(words_two)


# manual vectorizing 

In [4]:
# create a set with all unique words  (vocabulary)
all_uni_words = set()
all_uni_words.update(uni_words_one)

In [5]:
all_uni_words.update(uni_words_two)

In [6]:
# creating the vocabulary   
full_vocab = dict()
i = 0 

for words in all_uni_words : 
    full_vocab[words] =  i
    i += 1 

In [7]:
full_vocab

{'pets': 0,
 'dogs': 1,
 'surfing': 2,
 'popular': 3,
 'our': 4,
 'catching': 5,
 'a': 6,
 'fun': 7,
 'furry': 8,
 'water': 9,
 'are': 10,
 'is': 11,
 'sport': 12,
 'about': 13,
 'canine': 14,
 'story': 15,
 'this': 16,
 'animals': 17,
 'waves': 18}

In [13]:
one_freq = [0]*len(full_vocab)
two_freq = [0]*len(full_vocab)
all_words = [""]*len(full_vocab)


In [14]:
with open ("/home/jdiego/Documentos/MACHINE_LEARNING_DATA_SCIENCE/UNZIP_FOR_NOTEBOOKS_FINAL/One.txt") as f:
    one_text = f.read().lower().split()

In [15]:
for words in one_text : 
    word_ind = full_vocab[words]
    one_freq[word_ind] += 1 

In [16]:
with open ("/home/jdiego/Documentos/MACHINE_LEARNING_DATA_SCIENCE/UNZIP_FOR_NOTEBOOKS_FINAL/Two.txt") as f:
    two_text = f.read().lower().split()

In [17]:
for words in two_text : 
    word_ind = full_vocab[words]
    two_freq[word_ind] += 1 

In [19]:
for words in full_vocab : 
    word_ind = full_vocab[words]
    all_words[word_ind] = words 

In [20]:
all_words

['pets',
 'dogs',
 'surfing',
 'popular',
 'our',
 'catching',
 'a',
 'fun',
 'furry',
 'water',
 'are',
 'is',
 'sport',
 'about',
 'canine',
 'story',
 'this',
 'animals',
 'waves']

In [21]:
import pandas as pd 

In [22]:
df = pd.DataFrame(data=[one_freq,two_freq] , columns=all_words)

In [23]:
df

pets  dogs  surfing  popular  our  catching  a  fun  furry  water  are  is  \
0     1     2        0        0    1         0  1    0      1      0    1   1   
1     0     0        2        1    0         1  1    1      0      1    0   3   

   sport  about  canine  story  this  animals  waves  
0      0      1       1      1     1        1      0  
1      1      1       0      1     1        0      1

# using scikit learn

In [25]:
text = [" this is a line", 
        " this is another line", 
        " Other different line"]

In [36]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

In [39]:
cv = CountVectorizer()

In [40]:
sparse_matrix = cv.fit_transform(text)

In [41]:
sparse_matrix.todense()

matrix([[0, 0, 1, 1, 0, 1],
        [1, 0, 1, 1, 0, 1],
        [0, 1, 0, 1, 1, 0]])

In [42]:
cv.vocabulary_

{'this': 5, 'is': 2, 'line': 3, 'another': 0, 'other': 4, 'different': 1}

In [43]:
tdidf = TfidfTransformer()

In [44]:
sparse_matrix

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [45]:
results = tdidf.fit_transform(sparse_matrix)

In [46]:
results.todense()

matrix([[0.        , 0.        , 0.61980538, 0.48133417, 0.        ,
         0.61980538],
        [0.63174505, 0.        , 0.4804584 , 0.37311881, 0.        ,
         0.4804584 ],
        [0.        , 0.65249088, 0.        , 0.38537163, 0.65249088,
         0.        ]])

In [47]:
# all can be done in one step 

from sklearn.feature_extraction.text import TfidfVectorizer

In [48]:
tv = TfidfVectorizer()

In [49]:
tv_results = tv.fit_transform(text)

In [51]:
tv_results.todense()

matrix([[0.        , 0.        , 0.61980538, 0.48133417, 0.        ,
         0.61980538],
        [0.63174505, 0.        , 0.4804584 , 0.37311881, 0.        ,
         0.4804584 ],
        [0.        , 0.65249088, 0.        , 0.38537163, 0.65249088,
         0.        ]])